# Generated by Django 2.2.12 on 2023-04-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='num_likes',
        ),
    ]
